name: Sync Kindle Highlights
on: [push, workflow_dispatch]
jobs:
  sync-highlights:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync highlights
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/arkalim/kindle-to-notion:master
          run: node /code/dist/main.js
          options: |
            -v ${{ github.workspace }}:/code/resources 
            -e BOOK_DB_ID=${{ vars.BOOK_DB_ID }}
            -e NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}

      - name: Commit cache changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Commit cache changes
          add: sync.json

      - name: Push cache changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
